<!DOCTYPE html><html><head><meta http-equiv="content-type" content="text/html; charset=utf-8"><meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0" name="viewport"><meta content="yes" name="apple-mobile-web-app-capable"><meta content="black-translucent" name="apple-mobile-web-app-status-bar-style"><meta content="telephone=no" name="format-detection"><meta name="description"><title>Python Traceback 详解 | Geekpy's Blog</title><link rel="stylesheet" type="text/css" href="/css/normalize.css"><link rel="stylesheet" type="text/css" href="/css/highlight.css"><link rel="stylesheet" type="text/css" href="/css/very-simple.css"><link rel="stylesheet" type="text/css" href="//cdn.bootcss.com/font-awesome/4.5.0/css/font-awesome.min.css"><link rel="Shortcut Icon" type="image/x-icon" href="/favicon.ico"><link rel="alternate" type="application/atom+xml" href="/atom.xml"></head><body><!-- include the sidebar--><!-- include ./includes/sidebar.jade--><!-- Blog title and subtitle--><header><div class="container header"><a id="logo" href="/." class="title">Geekpy's Blog</a><span class="subtitle"></span><label id="toggle-menu" for="menu" onclick><i class="fa fa-bars"></i></label></div></header><!-- use checkbox hack for toggle nav-bar on small screens--><input id="menu" type="checkbox"><!-- Navigation Links--><nav id="nav"><div class="container"><a href="/" class="sidebar-nav-item active">Home</a><a href="/archives" class="sidebar-nav-item">Archives</a><a href="/about" class="sidebar-nav-item">About</a></div></nav><div id="header-margin-bar"></div><div class="wrapper"><div class="container post-header"><h1>Python Traceback 详解</h1></div></div><article><div class="container post"><p>刚接触Python的时候，简单的异常处理已经可以帮助我们解决大多数问题，但是随着逐渐地深入，我们会发现有很多情况下简单的异常处理已经无法解决问题了，如下代码，单纯的打印异常所能提供的信息会非常有限。</p>
<p>&lt;!--more--&gt;</p>
<p><figure class="highlight plain"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br></pre></td><td class="code"><pre><span class="line">def func1():</span><br><span class="line">    raise Exception(&quot;--func1 exception--&quot;)</span><br><span class="line"></span><br><span class="line"></span><br><span class="line">def main():</span><br><span class="line">    try:</span><br><span class="line">        func1()</span><br><span class="line">    except Exception as e:</span><br><span class="line">        print e</span><br><span class="line"></span><br><span class="line"></span><br><span class="line">if __name__ == &apos;__main__&apos;:</span><br><span class="line">    main()</span><br></pre></td></tr></table></figure></p>
<p>执行后输出如下：
<figure class="highlight plain"><table><tr><td class="gutter"><pre><span class="line">1</span><br></pre></td><td class="code"><pre><span class="line">--func1 exception--</span><br></pre></td></tr></table></figure></p>
<p>通过示例，我们发现普通的打印异常只有很少量的信息（通常是异常的value值），这种情况下我们很难定位在哪块代码出的问题，以及如何出现这种异常。那么到底要如何打印更加详细的信息呢？下面我们就来一一介绍。</p>
<h3>sys.exc_info和traceback object</h3>
<p>Python程序的traceback信息均来源于一个叫做<strong>traceback object</strong>的对象，而这个traceback object通常是通过函数sys.exc_info()来获取的，先来看一个例子：</p>
<p><figure class="highlight plain"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br></pre></td><td class="code"><pre><span class="line">import sys</span><br><span class="line"></span><br><span class="line"></span><br><span class="line">def func1():</span><br><span class="line">    raise NameError(&quot;--func1 exception--&quot;)</span><br><span class="line"></span><br><span class="line"></span><br><span class="line">def main():</span><br><span class="line">    try:</span><br><span class="line">        func1()</span><br><span class="line">    except Exception as e:</span><br><span class="line">        exc_type, exc_value, exc_traceback_obj = sys.exc_info()</span><br><span class="line">        print &quot;exc_type: %s&quot; % exc_type</span><br><span class="line">        print &quot;exc_value: %s&quot; % exc_value</span><br><span class="line">        print &quot;exc_traceback_obj: %s&quot; % exc_traceback_obj</span><br><span class="line"></span><br><span class="line"></span><br><span class="line">if __name__ == &apos;__main__&apos;:</span><br><span class="line">    main()</span><br></pre></td></tr></table></figure></p>
<p>执行后输出如下：
<figure class="highlight plain"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br></pre></td><td class="code"><pre><span class="line">exc_type: &lt;type &apos;exceptions.NameError&apos;&gt;</span><br><span class="line">exc_value: --func1 exception--</span><br><span class="line">exc_traceback_obj: &lt;traceback object at 0x7faddf5d93b0&gt;</span><br></pre></td></tr></table></figure></p>
<p>通过以上示例我们可以看出，sys.exc_info()获取了当前处理的exception的相关信息，并返回一个元组，元组的第一个数据是异常的类型(示例是NameError类型)，第二个返回值是异常的value值，第三个就是我们要的traceback object.</p>
<p>有了traceback object我们就可以通过traceback module来打印和格式化traceback的相关信息，下面我们就来看下traceback module的相关函数。</p>
<h3>traceback module</h3>
<p>Python的traceback module提供一整套接口用于提取，格式化和打印Python程序的stack traces信息，下面我们通过例子来详细了解下这些接口：</p>
<h4>print_tb</h4>
<p><figure class="highlight plain"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br></pre></td><td class="code"><pre><span class="line">import sys</span><br><span class="line">import traceback</span><br><span class="line"></span><br><span class="line"></span><br><span class="line">def func1():</span><br><span class="line">    raise NameError(&quot;--func1 exception--&quot;)</span><br><span class="line"></span><br><span class="line"></span><br><span class="line">def main():</span><br><span class="line">    try:</span><br><span class="line">        func1()</span><br><span class="line">    except Exception as e:</span><br><span class="line">        exc_type, exc_value, exc_traceback_obj = sys.exc_info()</span><br><span class="line">        traceback.print_tb(exc_traceback_obj)</span><br><span class="line"></span><br><span class="line"></span><br><span class="line">if __name__ == &apos;__main__&apos;:</span><br><span class="line">    main()</span><br></pre></td></tr></table></figure></p>
<p>输出：
<figure class="highlight plain"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br></pre></td><td class="code"><pre><span class="line">File &quot;&lt;ipython-input-23-52bdf2c9489c&gt;&quot;, line 11, in main</span><br><span class="line">    func1()</span><br><span class="line">File &quot;&lt;ipython-input-23-52bdf2c9489c&gt;&quot;, line 6, in func1</span><br><span class="line">    raise NameError(&quot;--func1 exception--&quot;)</span><br></pre></td></tr></table></figure></p>
<p>这里我们可以发现打印的异常信息更加详细了，下面我们了解下print_tb的详细信息：
<figure class="highlight plain"><table><tr><td class="gutter"><pre><span class="line">1</span><br></pre></td><td class="code"><pre><span class="line">traceback.print_tb(tb[, limit[, file]])</span><br></pre></td></tr></table></figure></p>
<ul>
<li>tb: 这个就是traceback object, 是我们通过sys.exc_info获取到的</li>
<li>limit: 这个是限制stack trace层级的，如果不设或者为None，就会打印所有层级的stack trace</li>
<li>file: 这个是设置打印的输出流的，可以为文件，也可以是stdout之类的file-like object。如果不设或为None，则输出到sys.stderr。</li>
</ul>
<h4>print_exception</h4>
<p><figure class="highlight plain"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br></pre></td><td class="code"><pre><span class="line">import sys</span><br><span class="line">import traceback</span><br><span class="line"></span><br><span class="line"></span><br><span class="line">def func1():</span><br><span class="line">    raise NameError(&quot;--func1 exception--&quot;)</span><br><span class="line"></span><br><span class="line">def func2():</span><br><span class="line">    func1()</span><br><span class="line"></span><br><span class="line">def main():</span><br><span class="line">    try:</span><br><span class="line">        func2()</span><br><span class="line">    except Exception as e:</span><br><span class="line">        exc_type, exc_value, exc_traceback_obj = sys.exc_info()</span><br><span class="line">        traceback.print_exception(exc_type, exc_value, exc_traceback_obj, limit=2, file=sys.stdout)</span><br><span class="line"></span><br><span class="line"></span><br><span class="line">if __name__ == &apos;__main__&apos;:</span><br><span class="line">    main()</span><br></pre></td></tr></table></figure></p>
<p>输出：
<figure class="highlight plain"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br></pre></td><td class="code"><pre><span class="line">Traceback (most recent call last):</span><br><span class="line">  File &quot;&lt;ipython-input-24-a68061acf52f&gt;&quot;, line 13, in main</span><br><span class="line">    func2()</span><br><span class="line">  File &quot;&lt;ipython-input-24-a68061acf52f&gt;&quot;, line 9, in func2</span><br><span class="line">    func1()</span><br><span class="line">NameError: --func1 exception--</span><br></pre></td></tr></table></figure></p>
<p>看下定义：
<figure class="highlight plain"><table><tr><td class="gutter"><pre><span class="line">1</span><br></pre></td><td class="code"><pre><span class="line">traceback.print_exception(etype, value, tb[, limit[, file]])</span><br></pre></td></tr></table></figure></p>
<ul>
<li>跟print_tb相比多了两个参数etype和value，分别是exception type和exception value，加上tb(traceback object)，正好是sys.exc_info()返回的三个值</li>
<li>另外，与print_tb相比，打印信息多了开头的&quot;Traceback (most...)&quot;信息以及最后一行的异常类型和value信息</li>
<li>还有一个不同是当异常为SyntaxError时，会有&quot;^&quot;来指示语法错误的位置</li>
</ul>
<h4>print_exc</h4>
<p>print_exc是简化版的print_exception, 由于exception type, value和traceback object都可以通过sys.exc_info()获取，因此print_exc()就自动执行exc_info()来帮助获取这三个参数了，也因此这个函数是我们的程序中最常用的，因为它足够简单
<figure class="highlight plain"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br></pre></td><td class="code"><pre><span class="line">import sys</span><br><span class="line">import traceback</span><br><span class="line"></span><br><span class="line"></span><br><span class="line">def func1():</span><br><span class="line">    raise NameError(&quot;--func1 exception--&quot;)</span><br><span class="line"></span><br><span class="line">def func2():</span><br><span class="line">    func1()</span><br><span class="line"></span><br><span class="line">def main():</span><br><span class="line">    try:</span><br><span class="line">        func2()</span><br><span class="line">    except Exception as e:</span><br><span class="line">        traceback.print_exc(limit=1, file=sys.stdout)</span><br><span class="line"></span><br><span class="line"></span><br><span class="line">if __name__ == &apos;__main__&apos;:</span><br><span class="line">    main()</span><br></pre></td></tr></table></figure></p>
<p>输出（由于limit=1，因此只有一个层级被打印出来）：
<figure class="highlight plain"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br></pre></td><td class="code"><pre><span class="line">Traceback (most recent call last):</span><br><span class="line">  File &quot;&lt;ipython-input-25-a1f5c73b97c4&gt;&quot;, line 13, in main</span><br><span class="line">    func2()</span><br><span class="line">NameError: --func1 exception--</span><br></pre></td></tr></table></figure></p>
<p>定义如下：
<figure class="highlight plain"><table><tr><td class="gutter"><pre><span class="line">1</span><br></pre></td><td class="code"><pre><span class="line">traceback.print_exc([limit[, file]])</span><br></pre></td></tr></table></figure></p>
<ul>
<li>只有两个参数，够简单</li>
</ul>
<h4>format_exc</h4>
<p><figure class="highlight plain"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br></pre></td><td class="code"><pre><span class="line">import logging</span><br><span class="line">import sys</span><br><span class="line">import traceback</span><br><span class="line">logger = logging.getLogger(&quot;traceback_test&quot;)</span><br><span class="line"></span><br><span class="line">def func1():</span><br><span class="line">    raise NameError(&quot;--func1 exception--&quot;)</span><br><span class="line"></span><br><span class="line">def func2():</span><br><span class="line">    func1()</span><br><span class="line"></span><br><span class="line">def main():</span><br><span class="line">    try:</span><br><span class="line">        func2()</span><br><span class="line">    except Exception as e:</span><br><span class="line">        logger.error(traceback.format_exc(limit=1, file=sys.stdout))</span><br><span class="line"></span><br><span class="line"></span><br><span class="line">if __name__ == &apos;__main__&apos;:</span><br><span class="line">    main()</span><br></pre></td></tr></table></figure></p>
<p>从这个例子可以看出有时候我们想得到的是一个字符串，比如我们想通过logger将异常记录在log里，这个时候就需要format_exc了，这个也是最常用的一个函数，它跟print_exc用法相同，只是不直接打印而是返回了字符串。</p>
<p>traceback module中还有一些其它的函数，但因为并不常用，就不在展开来讲，感兴趣的同学可以看下参考链接中的文档。</p>
<h3>获取线程中的异常信息</h3>
<p>通常情况下我们无法将多线程中的异常带回主线程，所以也就无法打印线程中的异常，而通过上边学到这些知识，我们可以对线程做如下修改，从而实现捕获线程异常的目的。
以下示例来自weidong的博客文章，稍有修改（见参考链接）
<figure class="highlight plain"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br><span class="line">21</span><br><span class="line">22</span><br><span class="line">23</span><br><span class="line">24</span><br><span class="line">25</span><br><span class="line">26</span><br><span class="line">27</span><br><span class="line">28</span><br><span class="line">29</span><br><span class="line">30</span><br><span class="line">31</span><br><span class="line">32</span><br><span class="line">33</span><br><span class="line">34</span><br><span class="line">35</span><br><span class="line">36</span><br><span class="line">37</span><br><span class="line">38</span><br><span class="line">39</span><br><span class="line">40</span><br><span class="line">41</span><br><span class="line">42</span><br><span class="line">43</span><br><span class="line">44</span><br><span class="line">45</span><br><span class="line">46</span><br><span class="line">47</span><br></pre></td><td class="code"><pre><span class="line">import threading</span><br><span class="line">import traceback</span><br><span class="line"></span><br><span class="line">def my_func():</span><br><span class="line">    raise BaseException(&quot;thread exception&quot;)</span><br><span class="line"></span><br><span class="line"></span><br><span class="line">class ExceptionThread(threading.Thread):</span><br><span class="line"></span><br><span class="line">    def __init__(self, group=None, target=None, name=None, args=(), kwargs=None, verbose=None):</span><br><span class="line">        &quot;&quot;&quot;</span><br><span class="line">        Redirect exceptions of thread to an exception handler.</span><br><span class="line">        &quot;&quot;&quot;</span><br><span class="line">        threading.Thread.__init__(self, group, target, name, args, kwargs, verbose)</span><br><span class="line">        if kwargs is None:</span><br><span class="line">            kwargs = &#123;&#125;</span><br><span class="line">        self._target = target</span><br><span class="line">        self._args = args</span><br><span class="line">        self._kwargs = kwargs</span><br><span class="line">        self._exc = None</span><br><span class="line"></span><br><span class="line">    def run(self):</span><br><span class="line">        try:</span><br><span class="line">            if self._target:</span><br><span class="line">                self._target()</span><br><span class="line">        except BaseException as e:</span><br><span class="line">            import sys</span><br><span class="line">            self._exc = sys.exc_info()</span><br><span class="line">        finally:</span><br><span class="line">            #Avoid a refcycle if the thread is running a function with</span><br><span class="line">            #an argument that has a member that points to the thread.</span><br><span class="line">            del self._target, self._args, self._kwargs</span><br><span class="line"></span><br><span class="line">    def join(self):</span><br><span class="line">        threading.Thread.join(self)</span><br><span class="line">        if self._exc:</span><br><span class="line">            msg = &quot;Thread &apos;%s&apos; threw an exception: %s&quot; % (self.getName(), self._exc[1])</span><br><span class="line">            new_exc = Exception(msg)</span><br><span class="line">            raise new_exc.__class__, new_exc, self._exc[2]</span><br><span class="line"></span><br><span class="line"></span><br><span class="line">t = ExceptionThread(target=my_func, name=&apos;my_thread&apos;)</span><br><span class="line">t.start()</span><br><span class="line">try:</span><br><span class="line">    t.join()</span><br><span class="line">except:</span><br><span class="line">    traceback.print_exc()</span><br></pre></td></tr></table></figure></p>
<p>输出如下：
<figure class="highlight plain"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br></pre></td><td class="code"><pre><span class="line">Traceback (most recent call last):</span><br><span class="line">  File &quot;/data/code/testcode/thread_exc.py&quot;, line 43, in &lt;module&gt;</span><br><span class="line">    t.join()</span><br><span class="line">  File &quot;/data/code/testcode/thread_exc.py&quot;, line 23, in run</span><br><span class="line">    self._target()</span><br><span class="line">  File &quot;/data/code/testcode/thread_exc.py&quot;, line 5, in my_func</span><br><span class="line">    raise BaseException(&quot;thread exception&quot;)</span><br><span class="line">Exception: Thread &apos;my_thread&apos; threw an exception: thread exception</span><br></pre></td></tr></table></figure></p>
<p>这样我们就得到了线程中的异常信息。</p>
<h3>参考链接</h3>
<p><a href="https://docs.python.org/2/library/traceback.html" target="_blank" rel="noopener">traceback官方文档</a></p>
<p><a href="http://swdtalent.github.io/weidong.github.com/2015-10-24/python-catch-thread-exception/" target="_blank" rel="noopener">weidong's blog</a></p>
</div><div class="container"><hr><div class="comment"></div><script src="//cdn1.lncld.net/static/js/3.0.4/av-min.js"></script>
<script src="//cdn.jsdelivr.net/npm/valine@1.1.6/dist/Valine.min.js"></script>
<script type="text/javascript">
var leancloud_appid = '';
var leancloud_appkey = '';
var valine_url = 'http://yoursite.com/2017/02/07/python_traceback/';
var valine_notify = false;
var valine_verify = false;
var valine_placeholder = 'input your comments here';
new Valine({
         av: AV, // source from av-min.js
         el: '.comment' ,
         notify: valine_notify,
         verify: valine_verify,
         app_id: leancloud_appid,
         app_key: leancloud_appkey,
         placeholder: valine_placeholder,
         path: valine_url
     });
</script></div></article><footer id="footer"><div class="container"><div class="bar"><div class="social"><a href="mailto:rebor.liu@gmail.com" target="_blank"><i class="fa fa-envelope-o"></i></a><a href="https://github.com/geekpy" target="_blank"><i class="fa fa-github"></i></a></div><div class="footer">© 2018 <a href="/" rel="nofollow">geekpy</a>. Powered by <a rel="nofollow" target="_blank" href="https://hexo.io">Hexo</a>. Theme <a target="_blank" href="https://github.com/lotabout/very-simple">very-simple</a>.</div></div></div></footer><link rel="stylesheet" type="text/css" href="//cdn.bootcss.com/fancybox/2.1.5/jquery.fancybox.css"><script src="//cdn.bootcss.com/jquery/2.0.3/jquery.min.js"></script><script src="//cdn.bootcss.com/fancybox/2.1.5/jquery.fancybox.pack.js"></script><script>$(document).ready(function() {
    $(".fancybox").fancybox();
});
</script></body></html>